services:
  control:
    image: ansible_control
    build: 
      context: .
      target: ansible_control
    volumes:
      - /home/niouby/hybird/ppd/pcore_project/tutorial/ansible:/home/ansible/ansible_work
    tty: true
  lb01:
    image: ansible_service
    build: 
      context: .
      target: ansible_service
    ports:
      - "80:80"
  app01:
    image: ansible_service
  app02:
    image: ansible_service
